name: Train and Push Docker

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  train-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Miniforge3
          miniforge-version: latest
          python-version: "3.12"
          activate-environment: mlflow-env
          use-mamba: true

      - name: Install MLflow
        run: |
          pip install --upgrade pip
          pip install mlflow==2.19.0 dagshub

      - name: Run MLflow Project
        shell: bash -l {0}
        working-directory: ./MLProject
        env:
          MLFLOW_TRACKING_URI: https://dagshub.com/RFDTYAA/credit-scoring-mlops.mlflow
          MLFLOW_TRACKING_USERNAME: RFDTYAA
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: mlflow run .

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/credit-scoring-api:latest
